#~ master λ➜


format ="$directory$git_branch [λ➜](bold blue) "
add_newline = false


[directory]
format="[$path](bold purple)"

[git_branch]
format=" [$symbol](bold red)[$branch](bold white)"
symbol=""
