#~ master λ➜


format ="$cmd_duration$directory$git_branch [λ➜](bold blue) "
add_newline = false


[directory]
format="[$path](bold purple)"

[git_branch]
format=" [$symbol](bold red)[$branch](bold white)"
symbol=""

[cmd_duration]
min_time=500
format="[$duration](bold white) "
